name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - name: Set timestamp
        run: echo "NOW=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_ENV

      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware

      - name: Publish release
        uses: svenstaro/upload-release-action@v2
        with:
          file: firmware/*.uf2
          file_glob: true
          tag: ${{ env.NOW }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
